Attempts to fix more TS2339 errors.
```
knex/knex-tests.ts(498,45): error TS2339: Property 'map' does not exist on type 'QueryBuilder'.
knex/knex-tests.ts(506,45): error TS2339: Property 'reduce' does not exist on type 'QueryBuilder'.
```

https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/119590526