Fix StatelessComponent interface
Props always pass to StatelessComponent even if we pass no props.
Example:

```js
function Test(props) {
  return <div>props: {JSON.stringify(props)}</div>
}

React.render(<Test />, document.body)
```
will render into `props: {}`
[jsfiddle](https://jsfiddle.net/LL25c28c/)

We need to fix this because otherwise we have error:
`Property 'propName' does not exist on type 'IntrinsicAttributes & (IMyInterface | undefined)'.`
for that code:
```js
const MyComponent: React.SFC<IMyInterface> = ({ propName }: IMyInterface) => {
  // ...
}
```