fix(jsdoc-to-markdown): correct module definition and update to v5 (#42732)
* fix(jsdoc-to-markdown): correct module definition and update to v5

- update module definition fixing errors like:
```bash
TSError: â¨¯ Unable to compile TypeScript:
index.ts:3:10 - error TS2339: Property 'render' does not exist on type
'typeof import("../node_modules/@types/jsdoc-to-markdown/index")'.

3 jsdoc2md.render({ files: 'src/*.js' }).then(...)
```
After this change the module is exported as regular CommonJS module
- update version to v5
- create backward compatible v4
- rewrite tests to match CommonJS module exports

https://github.com/jsdoc2md/jsdoc-to-markdown/blob/master/docs/API.md#jsdoc-to-markdown

Thanks!

* Fix v4 module definition as per PR comment

- module exports correct also for v4
- tests corrected for v4

/cc @amcasey