Fix compile errors
Change line 9779 from 
```ts
class QueryCollection<T> implements Array<T> {
```
to
```ts
class QueryCollection<T> extends Array<T> {
```
***Because I getting the error TS2420: Class 'QueryCollection<T>' incorrectly implements interface 'T[]'.***
***    Property 'find' is missing in type 'QueryCollection<T>'.***

After implementing find in .d.ts getting next error about method findIndex and so on.

Simplest way to fix it, was let QueryCollection  extends Array and not implement it.

***Typescript version***
1.8.7