🤖 Merge PR #44925 [socket.io]: 2.1.1 adds inherited EventEmitter methods to Server by @smacpherson64
* Set SocketIO.Server to extend EventEmitter

I am getting errors when trying to use `off` on the socket server listener. This is the part of the code that receives the type error:

```typescript
function watchForCancelledJobs() {
  const listener = function(jobId: string) {
    console.log({ type: "cancel-job", payload: { job: jobId } });
  };

  socket.on("cancel-job", listener);

  return () => {
    socket.off("cancel-job", listener); // Property 'off' does not exist on type 'Server'
  };
}
```

I believe the method comes from:
https://github.com/socketio/socket.io/blob/master/lib/socket.js#L81

* adds inheritied methods to socket.io server and adds tests

When updating and linting the files prettier made quite a few formatting changes.

Co-authored-by: Seth MacPherson <smacpherson@dmp.com>