Create react-filepond typescript definition test
It currently reports the error:

    ERROR: 22:1  strict-export-declare-modifiers  'declare' keyword is redundant here. See: https://github.com/Microsoft/dtslint/blob/master/docs/strict-export-declare-modifiers.md

        at C:\dev\DefinitelyTyped\node_modules\dtslint\bin\index.js:158:19
        at Generator.next (<anonymous>)
        at fulfilled (C:\dev\DefinitelyTyped\node_modules\dtslint\bin\index.js:5:58)
        at <anonymous>

But if I remove the 'declare' keyword on line 22, I get the error

    A 'declare' modifier is required for a top level declaration in a .d.ts file.

I want to use a class under one name in this file and another name
externally, what do I do here?