[selenium-webdriver] Fix typo in IPerfLoggingPrefs  (#50161)
* Fix typo in selenium-webdriver

According the [ChromeDriver docs](https://chromedriver.chromium.org/capabilities#TOC-perfLoggingPrefs-object) this field is called `traceCategories` not `tracingCategories`. Further I'm getting the following error when trying to use `tracingCategories`. Using `traceCategories` fixes it.

This is using ChromeDriver 87.0.4280.20 (c99e81631faa0b2a448e658c0dbd8311fb04ddbd-refs/branch-heads/4280@{#355}) on Windows.

```
InvalidArgumentError: invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: cannot parse perfLoggingPrefs
from invalid argument: unrecognized performance logging option: tracingCategories
    at Object.throwDecodedError (D:\github\andrewiggins\tachometer\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (D:\github\andrewiggins\tachometer\node_modules\selenium-webdriver\lib\http.js:655:13)
    at Executor.execute (D:\github\andrewiggins\tachometer\node_modules\selenium-webdriver\lib\http.js:581:28)
    at processTicksAndRejections (node:internal/process/task_queues:93:5) {
  remoteStacktrace: 'Backtrace:\n' +
    '\tOrdinal0 [0x007DECE3+3337443]\n' +
    '\tOrdinal0 [0x006BF041+2158657]\n' +
    '\tOrdinal0 [0x00546FA8+618408]\n' +
    '\tOrdinal0 [0x004B83DA+33754]\n' +
    '\tOrdinal0 [0x004BAB74+43892]\n' +
    '\tOrdinal0 [0x004B72A3+29347]\n' +
    '\tOrdinal0 [0x004BAB74+43892]\n' +
    '\tOrdinal0 [0x004B515D+20829]\n' +
    '\tOrdinal0 [0x004E4F6C+216940]\n' +
    '\tOrdinal0 [0x004E4C2E+216110]\n' +
    '\tOrdinal0 [0x004E5D4B+220491]\n' +
    '\tOrdinal0 [0x004E5BFC+220156]\n' +
    '\tOrdinal0 [0x004E181B+202779]\n' +
    '\tOrdinal0 [0x004C3D74+81268]\n' +
    '\tOrdinal0 [0x004C4D6E+85358]\n' +
    '\tOrdinal0 [0x004C4CF9+85241]\n' +
    '\tOrdinal0 [0x006D6F2C+2256684]\n' +
    '\tGetHandleVerifier [0x00962FAC+1478332]\n' +
    '\tGetHandleVerifier [0x00962AFD+1477133]\n' +
    '\tGetHandleVerifier [0x0096AAD8+1509864]\n' +
    '\tGetHandleVerifier [0x0096369E+1480110]\n' +
    '\tOrdinal0 [0x006CD6BD+2217661]\n' +
    '\tOrdinal0 [0x006D89AB+2263467]\n' +
    '\tOrdinal0 [0x006D8AEF+2263791]\n' +
    '\tOrdinal0 [0x006ED363+2347875]\n' +
    '\tBaseThreadInitThunk [0x76D3FA29+25]\n' +
    '\tRtlGetAppContainerNamedObjectPath [0x772B75F4+228]\n' +
    '\tRtlGetAppContainerNamedObjectPath [0x772B75C4+180]\n'
}
```

* Update selenium-webdirver tests