Attempts to fix new errors.
```
knex/knex-tests.ts(500,16): error TS2339: Property 'name' does not exist on type 'string'.
knex/knex-tests.ts(502,9): error TS2345: Argument of type '(names: string) => void' is not assignable to parameter of type '(value: any[]) => void | PromiseLike<void>'.
  Types of parameters 'names' and 'value' are incompatible.
    Type 'string' is not assignable to type 'any[]'.
```

https://travis-ci.org/DefinitelyTyped/DefinitelyTyped/builds/119592117