... yeah; an required parameter cannot follow an optional one
```
ERROR: 5825:61  expect                      TypeScript@next compile error: 
A required parameter cannot follow an optional parameter.
```