[@wordpress/components,next-pwa] Fix tests with TS 5.3 (#66899)
* [@wordpress/components] Fix tests with TS 5.3

Fixes
```
Error in wordpress__components
Error: /home/runner/work/DefinitelyTyped/DefinitelyTyped/types/wordpress__components/wordpress__components-tests.tsx:575:2
ERROR: 575:2  expect  TypeScript@5.3 compile error:
Type '{ children: never[]; className: string; notices: { id: string; content: string; actions: { label: string; url: string; }[]; }[]; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'children' does not exist on type 'IntrinsicAttributes & Props'.

    at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:235:11)
    at runTests (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint/src/index.ts:176:5)
```

* [next-pwa] Fix tests with TS 5.3

Fixes
```
Error in next-pwa
Error: Errors in typescript@5.3 for external dependencies:
Error: node_modules/next/dist/client/components/router-reducer/router-reducer-types.d.ts(44,13): error TS2304: Cannot find name 'Location'.
Error: node_modules/next/dist/client/components/router-reducer/router-reducer-types.d.ts(50,13): error TS2304: Cannot find name 'Location'.
Error: node_modules/next/dist/client/components/router-reducer/router-reducer-types.d.ts(101,21): error TS2304: Cannot find name 'Location'.
```

* f