🤖 Merge PR #59159 node/v12: add missing "readFloatBE" by @jesec
```
error TS2551: Property 'readFloatBE' does not exist on type 'Buffer'.

Did you mean 'readFloatLE'?
```

'readFloatBE' was erroneously removed in #58626.

This change restores it and copies Buffer tests from v14.