Fix passReqToCallback type in passport-azure-ad (#36030)
* Fix passReqToCallback type

Fixes the following compilation error:

error TS2345: Argument of type '{ allowHttpForRedirectUrl: true; clientID: string; clientSecret: string | undefined; identityMetadata: string; passReqToCallback: boolean; redirectUrl: string; responseMode: "form_post"; responseType: "code id_token"; scope: string[]; validateIssuer: false; }' is not assignable to parameter of type 'IOIDCStrategyOption'.
  Object literal may only specify known properties, and 'passReqToCallback' does not exist in type 'IOIDCStrategyOption'.

69     passReqToCallback: false,

* Update according to feedback from @rbuckton
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/36030#discussion_r293151320

* Fix leftover "true"