Update react-dom.d.ts
It wasn't usable.

import React = require("react");
import ReactDOM = require("react-dom");

// console.log(form.ContactForm);

ReactDOM.render(React.createElement(form.ContactForm), document.getElementById("four"));

Compilation error
 error TS2339: Property 'render' does not exist on type 'typeof __ReactDom'.