🤖 Merge PR #54932 update to passport-local-mongoose 6.1.0 by @troysandal
* upgrade to passport-local-mongoose 6.1.0

* run prettier on my changes

* fix things that prettier caused

I forgot to run `npm run test passport-local-mongoose` before checking
in my last change and didn't realize that running prettier had broken
the linter rules.

* Address PR comments from peterblazejewicz

* remove dt-header at maintainers suggestion

* Restore type refernces, lower TypeScript Version

Per PR comments I restored missing type references and lowered
the TypeScript version as much as possible.  At versions lower than 3.7
the following errors occur:

```
Error: Errors in typescript@3.6 for external dependencies:
node_modules/mongoose/index.d.ts(2568,8): error TS2456: Type alias 'LeanArray' circularly references itself.
node_modules/mongoose/index.d.ts(2568,65): error TS2315: Type 'LeanArray' is not generic.
node_modules/mongoose/index.d.ts(2579,27): error TS2315: Type 'LeanArray' is not generic.

    at /Users/troy/depot/tmp/DefinitelyTyped/node_modules/dtslint/bin/index.js:207:19
    at Generator.next (<anonymous>)
    at fulfilled (/Users/troy/depot/tmp/DefinitelyTyped/node_modules/dtslint/bin/index.js:6:58)
```